<?php


function layout_builder_theming_theme_registry_alter(&$theme_registry) {

  $route_name = \Drupal::routeMatch()->getRouteName();
  $route_is_admin = \Drupal::service('router.admin_context')->isAdminRoute();

  // Just do that if the theme is 'admin' and the page is the add or edit node form.
  if($route_is_admin && ($route_name == 'entity.node.edit_form' || $route_name == 'node.add')) {

    /** @var \Drupal\Core\File\FileSystemInterface $file_system */
    $file_system = \Drupal::service('file_system');

    $defaultThemeName = \Drupal::config('system.theme')->get('default');
    $theme_path = \Drupal::service('extension.list.theme')->getPath($defaultThemeName);
    $templates_path = $theme_path . '/templates';

    $paragraph_types = _layout_paragraphs_get_paragraph_types();
    // Adding 'default' paragraph type to search paragraphs.html.twig template file inside default theme.
    array_unshift($paragraph_types);

    foreach ($paragraph_types as $type) {

      if($type == 'default') {
        $file_name = 'paragraph.html.twig';
        $template_name = 'paragraph';
        $template_file = 'paragraph';
      } else {
        $changedType = str_replace("_","-",$type);
        $file_name = 'paragraph--' . $changedType . '.html.twig';
        $template_name = 'paragraph__' . $type;
        $template_file = 'paragraph--' . $changedType;
      }

      // Scan for the template file inside template folder and subfolders.
      $file_exists = $file_system->scanDirectory($templates_path, '/^' . $file_name . '/');

      // If file exists, modify the paths for the theme template file.
      if(count($file_exists) > 0) {
        // Get the template file directory name (path).
        $templates_path = $file_system->dirname(array_key_first($file_exists));

        $theme_registry[$template_name]['render element'] = 'elements';
        $theme_registry[$template_name]['type'] = 'theme_engine';
        $theme_registry[$template_name]['theme path'] = $theme_path;
        $theme_registry[$template_name]['template'] = $template_file;
        $theme_registry[$template_name]['path'] = $templates_path;
        $theme_registry[$template_name]['preprocess functions'] = $theme_registry['paragraph']['preprocess functions'];
      }
    }
  }
}


/**
 * Helper function to get a list of paragraph types by machine name
 *
 * @return array
 */

function _layout_paragraphs_get_paragraph_types(){
  $paragraph_bundles = \Drupal::service('entity_type.bundle.info')->getBundleInfo('paragraph');

  return array_keys($paragraph_bundles);
}
